Added docker pre-check

diff --git a/pmm/run b/pmm/run
--- a/pmm/run
+++ b/pmm/run
@@ -119,6 +119,14 @@ logs() {
   docker logs ${PRODUCT_SERVER}
 }
 
+require_docker() {
+  DOCKER="docker"
+  if ! command -v "${DOCKER}" &>/dev/null; then
+    error "'${DOCKER}' is required"
+  fi
+  info "Reqired '${DOCKER}' is installed"
+}
+
 initialization() {
   local INIT_CNF
 
@@ -133,6 +141,8 @@ initialization() {
 
   [[ $(grep -c "example-host" ${INIT_CNF}) -eq 1 ]] && error "'${INIT_CNF}' contains default example settings"
   info "Initializing configuration for '${PRODUCT}'"
+
+  require_docker
 }
 
 help() {
